Repository KBS-ASD/message-bus-performance-testing, pull requests merged in 2018-12, with the labels that each got.

#39 #21 start api controller, connected infrastructure to controller.
  KBS.sln
  src/KBS.Controller/Controllers/TestController.cs
  src/KBS.Controller/Controllers/ValuesController.cs
  src/KBS.Controller/KBS.Controller.csproj
  src/KBS.Controller/Startup.cs
  src/KBS.Controller/web.config
  src/KBS.FauxApplication/Configuration.cs
  src/KBS.Infrastructure/Class1.cs
  src/KBS.Infrastructure/IManager.cs
  src/KBS.Infrastructure/KBS.Infrastructure.csproj
  src/KBS.Infrastructure/Manager.cs
Labels: story

#44 Add Swagger and rename Configuration to TestConfiguration
  src/KBS.Controller/Controllers/TestController.cs
  src/KBS.Controller/KBS.Controller.csproj
  src/KBS.Controller/Models/TestConfiguration.cs
  src/KBS.Controller/Program.cs
  src/KBS.Controller/Startup.cs
  src/KBS.Controller/web.config
  src/KBS.FauxApplication/ITestConfiguration.cs
  src/KBS.Infrastructure/IManager.cs
  src/KBS.Infrastructure/Manager.cs
Labels: feature

#48 Update README.md
  README.md
Labels: task

#49 #42 Rename manager
  src/KBS.Controller/Controllers/TestController.cs
  src/KBS.Infrastructure/IManager.cs
  src/KBS.Infrastructure/ITestEnviroment.cs
  src/KBS.Infrastructure/KBS.Infrastructure.csproj
  src/KBS.Infrastructure/Manager.cs
  src/KBS.Infrastructure/Models/TestEnviroment.cs
Labels: task

#59 #54 Add CodeMaid config file
  CodeMaid.config
Labels: task
