Repository KBS-ASD/message-bus-performance-testing, pull requests merged in 2019-01, with the labels that each got.

#64 Remove unnecessary console write
  src/KBS.MessageBus/MessageCaptureContext.cs
Labels: bug

#70 Trigger webjob using controller
  src/KBS.Benchmark/BenchmarkContext.cs
  src/KBS.Benchmark/States/Cleanup.cs
  src/KBS.Benchmark/States/CreateBusControl.cs
  src/KBS.Benchmark/States/CreateTelemetryClient.cs
  src/KBS.Configuration/BaseConfiguration.cs
  src/KBS.Configuration/BenchmarkConfiguration.cs
  src/KBS.Configuration/ControllerConfiguration.cs
  src/KBS.Configuration/TelemetryClientConfiguration.cs
  src/KBS.Configuration/TestCaseConfiguration.cs
  src/KBS.Configuration/TransportConfiguration.cs
  src/KBS.ConfigurationTests/BenchmarkConfigurationTests.cs
  src/KBS.ConfigurationTests/ControllerConfigurationTests.cs
  src/KBS.ConfigurationTests/KBS.ConfigurationTests.csproj
  src/KBS.Controller/Controllers/TestController.cs
  src/KBS.Controller/Model/ISimpleBenchmarkConfiguration.cs
  src/KBS.Controller/Program.cs
  src/KBS.Controller/Startup.cs
  src/KBS.Controller/web.config
  src/KBS.ControllerTests/KBS.ControllerTests.csproj
  src/KBS.Data/Constants/EnvironmentVariables.cs
  src/KBS.Data/Constants/TelemetryEventNames.cs
  src/KBS.Data/Constants/TelemetryEventPropertyNames.cs
  src/KBS.FauxApplication/Program.cs
  src/KBS.FauxApplicationTests/KBS.FauxApplicationTests.csproj
  src/KBS.InfrastructureTests/KBS.InfrastructureTests.csproj
  src/KBS.MessageBus/BusControl.cs
  src/KBS.MessageBus/MessageCaptureContext.cs
  src/KBS.MessageBus/TransportFactory.cs
  src/KBS.MessageBusTests/KBS.MessageBusTests.csproj
  src/KBS.MessageBusTests/TransportFactoryTests.cs
  src/KBS.Telemetry/Clients/ApplicationInsightsTelemetryClient.cs
  src/KBS.Telemetry/Clients/ITelemetryClient.cs
  src/KBS.Telemetry/Clients/InMemoryTelemetryClient.cs
  src/KBS.Telemetry/TelemetryClientFactory.cs
  src/KBS.TestCases/TestCaseFactory.cs
  src/KBS.TestCases/TestCases/ConsumeConsumer/ConsumeConsumerTestCase.cs
  src/KBS.TestCases/TestCases/RequestResponse/RequestResponseTestCase.cs
  src/KBS.TestCases/TestCases/TestCase.cs
  src/KBS.TestCases/TestCases/Webshop/Consumers/Shop.cs
  src/KBS.TestCases/TestCases/Webshop/WebshopTestCase.cs
  src/KBS.TestCases/Utilities/Randomizer.cs
Labels: feature

#72 Feature/save result azure storage blobs
  src/KBS.Configuration/BaseConfiguration.cs
  src/KBS.Configuration/BenchmarkConfiguration.cs
  src/KBS.Configuration/ControllerConfiguration.cs
  src/KBS.Configuration/TelemetryClientConfiguration.cs
  src/KBS.Configuration/TestCaseConfiguration.cs
  src/KBS.Configuration/TransportConfiguration.cs
  src/KBS.ConfigurationTests/ConfigurationTests.cs
  src/KBS.Controller/Controllers/BenchmarkController.cs
  src/KBS.Controller/Controllers/ResultsController.cs
  src/KBS.Controller/Model/SimpleBenchmarkConfiguration.cs
  src/KBS.FauxApplication/Program.cs
  src/KBS.MessageBus/BusControl.cs
  src/KBS.Telemetry/Clients/InMemoryTelemetryClient.cs
  src/KBS.Telemetry/KBS.Telemetry.csproj
  src/KBS.TestCases/TestCases/ConsumeConsumer/ConsumeConsumerTestCase.cs
  src/KBS.TestCases/TestCases/RequestResponse/RequestResponseTestCase.cs
  src/KBS.TestCases/TestCases/TestCase.cs
  src/KBS.TestCases/TestCases/Webshop/WebshopTestCase.cs
  src/KBS.TestCases/Utilities/Randomizer.cs
Labels: feature

#73 Escaped json fix
  src/KBS.Controller/Controllers/BenchmarkController.cs
Labels: bug

#74 Fix configuration names in KBS.Controller
  src/KBS.Controller/Model/SimpleBenchmarkConfiguration.cs
Labels: bug

#76 Add configuration to json output
  src/KBS.Configuration/BaseConfiguration.cs
  src/KBS.Data/Model/SimpleBenchmarkConfiguration.cs
  src/KBS.Telemetry/Clients/InMemoryTelemetryClient.cs
Labels: feature

#77 Add ConsumeObserver to fix azure service bus benchmark
  src/KBS.Benchmark/States/CreateBusControl.cs
  src/KBS.Data/Enum/TelemetryEventType.cs
  src/KBS.MessageBus/MessageCaptureContext.cs
  src/KBS.MessageBus/Observers/ConsumeObserver.cs
  src/KBS.MessageBus/Observers/ReceiveObserver.cs
  src/KBS.Telemetry/Clients/InMemoryTelemetryClient.cs
Labels: bug, feature
